language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0

install:
  - gem install bundler:1.17.3
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
